### ISSUE TITLE
Getting an Error for radioButton When preloading wizard data 

### ISSUE THREAD

**Issue by neolanders** [formio/ng2-formio#79]
ex:

```
export class WizardComponent {

 public submission: any = {
    data: {
      emplacement: 'rueRuelle' // radio button value
    }
  };
```
**HTML:**
```
<formio [submission]="submission" (submit)="onSubmit($event)" src="https://APP_URL/wizard"></formio>
```

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at RadioComponent.setValueAt (Radio.js:94)
    at RadioComponent.setValue (Base.js:789)
    at Components.js:253
    at arrayEach (_arrayEach.js:15)
    at forEach (forEach.js:38)
    at FormioWizard.setValue (Components.js:243)
    at formio.form.js:145
    at ZoneDelegate.invoke (zone.js:365)
    at Object.onInvoke (core.es5.js:4145)
    at ZoneDelegate.invoke (zone.js:364)
    at Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.es5.js:4136)
    at ZoneDelegate.invokeTask (zone.js:397)
    at RadioComponent.setValueAt (Radio.js:94)
    at RadioComponent.setValue (Base.js:789)
    at Components.js:253
    at arrayEach (_arrayEach.js:15)
    at forEach (forEach.js:38)
    at FormioWizard.setValue (Components.js:243)
    at formio.form.js:145
    at ZoneDelegate.invoke (zone.js:365)
    at Object.onInvoke (core.es5.js:4145)
    at ZoneDelegate.invoke (zone.js:364)
    at Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.es5.js:4136)
    at ZoneDelegate.invokeTask (zone.js:397)
    at resolvePromise (zone.js:712) [angular]
    at :3333/polyfills.bundle.js:11269:17 [angular]
    at :3333/polyfills.bundle.js:11285:33 [angular]
    at Object.onInvoke (core.es5.js:4145) [angular]
    at Zone.run (zone.js:125) [angular => angular]
    at :3333/polyfills.bundle.js:11391:57 [angular]
    at Object.onInvokeTask (core.es5.js:4136) [angular]
    at ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at HTMLButtonElement.ZoneTask.invoke (zone.js:464) [<root>]

**Comment by neolanders** [comment]
Actually there is 3 differentes issue related to radio-buttons:

1 - Will inspecting the html after render, I can see id="xxx_undefined"
ex:
<input name="data[emplacement]" type="radio" class="" id="undefined-rueRuelle" value="rueRuelle">

2-  Will canceling inline layout, my radio-buttons are style inline

3 - Will setting submission, I'm getting an error
