### ISSUE TITLE
An error is through when rendering an HTML element

### ISSUE THREAD

**Issue by neolanders** [formio/ng2-formio#80]
After adding an HTML element to our form, we are getting the fallowing errors:

```
EXCEPTION: Uncaught (in promise): InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.
Error: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.
    at https://local.servicesenligne:3333/0.chunk.js:33242:24
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    at forEach (https://local.servicesenligne:3333/0.chunk.js:39845:10)
    at HTMLComponent.build (https://local.servicesenligne:3333/0.chunk.js:33241:26)
    at Object.create (https://local.servicesenligne:3333/0.chunk.js:16815:10)
    at PanelComponent.addComponent (https://local.servicesenligne:3333/0.chunk.js:13176:29)
    at https://local.servicesenligne:3333/0.chunk.js:13235:23
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    at forEach (https://local.servicesenligne:3333/0.chunk.js:39845:10)
    at PanelComponent.addComponents (https://local.servicesenligne:3333/0.chunk.js:13234:26)
    at PanelComponent.build (https://local.servicesenligne:3333/0.chunk.js:33380:12)
    at Object.create (https://local.servicesenligne:3333/0.chunk.js:16815:10)
    at FormioForm.addComponent (https://local.servicesenligne:3333/0.chunk.js:13176:29)
    at https://local.servicesenligne:3333/0.chunk.js:13235:23
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    
    
      
    
Unhandled Promise rejection: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name. ; Zone: angular ; Task: Promise.then ; Value: DOMException: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.
    at https://local.servicesenligne:3333/0.chunk.js:33242:24
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    at forEach (https://local.servicesenligne:3333/0.chunk.js:39845:10)
    at HTMLComponent.build (https://local.servicesenligne:3333/0.chunk.js:33241:26)
    at Object.create (https://local.servicesenligne:3333/0.chunk.js:16815:10)
    at PanelComponent.addComponent (https://local.servicesenligne:3333/0.chunk.js:13176:29)
    at https://local.servicesenligne:3333/0.chunk.js:13235:23
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    at forEach (https://local.servicesenligne:3333/0.chunk.js:39845:10)
    at PanelComponent.addComponents (https://local.servicesenligne:3333/0.chunk.js:13234:26)
    at PanelComponent.build (https://local.servicesenligne:3333/0.chunk.js:33380:12)
    at Object.create (https://local.servicesenligne:3333/0.chunk.js:16815:10)
    at FormioForm.addComponent (https://local.servicesenligne:3333/0.chunk.js:13176:29)
    at https://local.servicesenligne:3333/0.chunk.js:13235:23
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9) Error: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.
    at https://local.servicesenligne:3333/0.chunk.js:33242:24
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    at forEach (https://local.servicesenligne:3333/0.chunk.js:39845:10)
    at HTMLComponent.build (https://local.servicesenligne:3333/0.chunk.js:33241:26)
    at Object.create (https://local.servicesenligne:3333/0.chunk.js:16815:10)
    at PanelComponent.addComponent (https://local.servicesenligne:3333/0.chunk.js:13176:29)
    at https://local.servicesenligne:3333/0.chunk.js:13235:23
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
    at forEach (https://local.servicesenligne:3333/0.chunk.js:39845:10)
    at PanelComponent.addComponents (https://local.servicesenligne:3333/0.chunk.js:13234:26)
    at PanelComponent.build (https://local.servicesenligne:3333/0.chunk.js:33380:12)
    at Object.create (https://local.servicesenligne:3333/0.chunk.js:16815:10)
    at FormioForm.addComponent (https://local.servicesenligne:3333/0.chunk.js:13176:29)
    at https://local.servicesenligne:3333/0.chunk.js:13235:23
    at arrayEach (https://local.servicesenligne:3333/0.chunk.js:17343:9)
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
```

**Comment by StephenOTT** [comment]
Closed through the PR
