### ISSUE TITLE
```ionic-app-scripts build --prod``` errors with rc8

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#90]
testing out with sample ionic app compilation  throws errors - (with rc6-rc14...)
```npm run ionic:build --prod```

small error:
```missing node_mnodules/ng2-formio/src/formio.component.css```
bypassed by creating an empty file...

another issue:

[16:43:23]  Error: ./~/formiojs/build/formio.js Module build failed: RangeError: Maximum call stack size exceeded at 
            getCheckFlags (./node_modules/typescript/lib/typescript.js:26030:31) at 
            getTypeOfSymbol (./node_modules/typescript/lib/typescript.js:29477:17) at 
            getTypeOfParameter (./node_modules/typescript/lib/typescript.js:39794:24) 
            at getTypeAtPosition (./node_modules/typescript/lib/typescript.js:39805:57) 
            at checkApplicableSignature 
            (./node_modules/typescript/lib/typescript.js:38808:37) at chooseOverload 
            (./node_modules/typescript/lib/typescript.js:39316:30) at resolveCall 
            (./node_modules/typescript/lib/typescript.js:39220:26) at 
            resolveNewExpression (./node_modules/typescript/lib/typescript.js:39482:33) 
            at resolveSignature (./node_modules/typescript/lib/typescript.js:39639:28) 
            at getResolvedSignature 
            (./node_modules/typescript/lib/typescript.js:39669:26) @ 
            ```./~/ng2-formio/src/formio.component.js 9:13-32``` @ ./src/pages/object.ngfactory.ts @ 
            ./src/app/app.module.ngfactory.ts @ ./src/app/main.ts 
```Error: ./~/formiojs/build/formio.js```
Module build failed: RangeError: Maximum call stack size exceeded
    at getCheckFlags (./node_modules/typescript/lib/typescript.js:26030:31)
    at getTypeOfSymbol (./node_modules/typescript/lib/typescript.js:29477:17)
    at getTypeOfParameter (./node_modules/typescript/lib/typescript.js:39794:24)
    at getTypeAtPosition (./node_modules/typescript/lib/typescript.js:39805:57)
    at checkApplicableSignature (./node_modules/typescript/lib/typescript.js:38808:37)
    at chooseOverload (./node_modules/typescript/lib/typescript.js:39316:30)
    at resolveCall (./node_modules/typescript/lib/typescript.js:39220:26)
    at resolveNewExpression (./node_modules/typescript/lib/typescript.js:39482:33)
    at resolveSignature (./node_modules/typescript/lib/typescript.js:39639:28)
    at getResolvedSignature (./node_modules/typescript/lib/typescript.js:39669:26)
 ```@ ./~/ng2-formio/src/formio.component.js 9:13-32``` @ ./src/pages/test/test.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at new BuildError (./node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (./node_modules/@ionic/app-scripts/dist/webpack.js:119:28)
    at ./node_modules/webpack/lib/Compiler.js:256:15
    at Compiler.emitRecords (./node_modules/webpack/lib/Compiler.js:351:37)
    at ./node_modules/webpack/lib/Compiler.js:249:12
    at ./node_modules/webpack/lib/Compiler.js:344:11
    at next (./node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (./node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (./node_modules/tapable/lib/Tapable.js:158:13)
```

**Comment by mtsang** [comment]
The line it is complaining about (./~/ng2-formio/src/formio.component.js 9:13-32) is 
var Formio = require('formiojs'); ... 

@travist any ideas as to what might be causing this  / what i can do to help debug?

**Comment by travist** [comment]
I am actually looking at this right now. I may try to turn it into a ```import``` command and see if that has an effect.

**Comment by mtsang** [comment]
ng2-formio is in  node-modules/formiojs/package.json 
It doesn't seem like it really should be there... is it possible that it's causing a circular dependency?

Also, is it possible that formiojs is importing itself (or other some other library that depends on itself, creating a circular dependency? (quick grep seems like it's formiojs/form that it imports...)

**Comment by travist** [comment]
Ah... I will get new release out today that cleans all this up. Thank you!

**Comment by travist** [comment]
So, I just took a look and do not see ng2-formio within the package.json of formiojs. I see that it is within the ```_requiredBy``` and ```_location``` but that is done during the installation of the module so I don't think that is it. Pretty frustrating since the errors that are thrown do not really indicate the real problem, and since it is fine with regular builds, I am having a hard time figuring out the cause here. Open to other suggestions.

**Comment by mtsang** [comment]
ah - my bad.
i read some people suggesting trying to use source maps on the call stack helping to help to track down the circular dependency...

maybe something like https://github.com/evanw/node-source-map-support ?

**Comment by mtsang** [comment]
a good writeup as to how easy it is to create an infinite loop in angular... https://github.com/angular/angular/issues/7930
